/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardCatalogDepartmentIndexRouteImport } from './routes/dashboard/catalog/department/index'
import { Route as DashboardCatalogDepartmentDepartmentIdRouteImport } from './routes/dashboard/catalog/department/$departmentId'
import { Route as DashboardCatalogSubdepartmentSubdepartmentIdRouteImport } from './routes/dashboard/catalog/subdepartment/$subdepartmentId'
import { Route as DashboardNursingCaregiverIndexRouteImport } from './routes/dashboard/nursing/caregiver/index'
import { Route as DashboardNursingConsultationFeeIndexRouteImport } from './routes/dashboard/nursing/consultation-fee/index'
import { Route as DashboardNursingDoctorIndexRouteImport } from './routes/dashboard/nursing/doctor/index'
import { Route as DashboardNursingDoctorDoctorIdRouteImport } from './routes/dashboard/nursing/doctor/$doctorId'
import { Route as DashboardNursingNurseIndexRouteImport } from './routes/dashboard/nursing/nurse/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCatalogDepartmentIndexRoute =
  DashboardCatalogDepartmentIndexRouteImport.update({
    id: '/catalog/department/',
    path: '/catalog/department/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCatalogDepartmentDepartmentIdRoute =
  DashboardCatalogDepartmentDepartmentIdRouteImport.update({
    id: '/catalog/department/$departmentId',
    path: '/catalog/department/$departmentId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCatalogSubdepartmentSubdepartmentIdRoute =
  DashboardCatalogSubdepartmentSubdepartmentIdRouteImport.update({
    id: '/catalog/subdepartment/$subdepartmentId',
    path: '/catalog/subdepartment/$subdepartmentId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingCaregiverIndexRoute =
  DashboardNursingCaregiverIndexRouteImport.update({
    id: '/nursing/caregiver/',
    path: '/nursing/caregiver/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingConsultationFeeIndexRoute =
  DashboardNursingConsultationFeeIndexRouteImport.update({
    id: '/nursing/consultation-fee/',
    path: '/nursing/consultation-fee/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingDoctorIndexRoute =
  DashboardNursingDoctorIndexRouteImport.update({
    id: '/nursing/doctor/',
    path: '/nursing/doctor/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingDoctorDoctorIdRoute =
  DashboardNursingDoctorDoctorIdRouteImport.update({
    id: '/nursing/doctor/$doctorId',
    path: '/nursing/doctor/$doctorId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingNurseIndexRoute =
  DashboardNursingNurseIndexRouteImport.update({
    id: '/nursing/nurse/',
    path: '/nursing/nurse/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/catalog/department/$departmentId': typeof DashboardCatalogDepartmentDepartmentIdRoute
  '/dashboard/catalog/subdepartment/$subdepartmentId': typeof DashboardCatalogSubdepartmentSubdepartmentIdRoute
  '/dashboard/nursing/doctor/$doctorId': typeof DashboardNursingDoctorDoctorIdRoute
  '/dashboard/catalog/department/': typeof DashboardCatalogDepartmentIndexRoute
  '/dashboard/nursing/caregiver/': typeof DashboardNursingCaregiverIndexRoute
  '/dashboard/nursing/consultation-fee/': typeof DashboardNursingConsultationFeeIndexRoute
  '/dashboard/nursing/doctor/': typeof DashboardNursingDoctorIndexRoute
  '/dashboard/nursing/nurse/': typeof DashboardNursingNurseIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/dashboard/catalog/department/$departmentId': typeof DashboardCatalogDepartmentDepartmentIdRoute
  '/dashboard/catalog/subdepartment/$subdepartmentId': typeof DashboardCatalogSubdepartmentSubdepartmentIdRoute
  '/dashboard/nursing/doctor/$doctorId': typeof DashboardNursingDoctorDoctorIdRoute
  '/dashboard/catalog/department': typeof DashboardCatalogDepartmentIndexRoute
  '/dashboard/nursing/caregiver': typeof DashboardNursingCaregiverIndexRoute
  '/dashboard/nursing/consultation-fee': typeof DashboardNursingConsultationFeeIndexRoute
  '/dashboard/nursing/doctor': typeof DashboardNursingDoctorIndexRoute
  '/dashboard/nursing/nurse': typeof DashboardNursingNurseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/catalog/department/$departmentId': typeof DashboardCatalogDepartmentDepartmentIdRoute
  '/dashboard/catalog/subdepartment/$subdepartmentId': typeof DashboardCatalogSubdepartmentSubdepartmentIdRoute
  '/dashboard/nursing/doctor/$doctorId': typeof DashboardNursingDoctorDoctorIdRoute
  '/dashboard/catalog/department/': typeof DashboardCatalogDepartmentIndexRoute
  '/dashboard/nursing/caregiver/': typeof DashboardNursingCaregiverIndexRoute
  '/dashboard/nursing/consultation-fee/': typeof DashboardNursingConsultationFeeIndexRoute
  '/dashboard/nursing/doctor/': typeof DashboardNursingDoctorIndexRoute
  '/dashboard/nursing/nurse/': typeof DashboardNursingNurseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/catalog/department/$departmentId'
    | '/dashboard/catalog/subdepartment/$subdepartmentId'
    | '/dashboard/nursing/doctor/$doctorId'
    | '/dashboard/catalog/department/'
    | '/dashboard/nursing/caregiver/'
    | '/dashboard/nursing/consultation-fee/'
    | '/dashboard/nursing/doctor/'
    | '/dashboard/nursing/nurse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/login'
    | '/dashboard/catalog/department/$departmentId'
    | '/dashboard/catalog/subdepartment/$subdepartmentId'
    | '/dashboard/nursing/doctor/$doctorId'
    | '/dashboard/catalog/department'
    | '/dashboard/nursing/caregiver'
    | '/dashboard/nursing/consultation-fee'
    | '/dashboard/nursing/doctor'
    | '/dashboard/nursing/nurse'
  id:
    | '__root__'
    | '/dashboard'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/catalog/department/$departmentId'
    | '/dashboard/catalog/subdepartment/$subdepartmentId'
    | '/dashboard/nursing/doctor/$doctorId'
    | '/dashboard/catalog/department/'
    | '/dashboard/nursing/caregiver/'
    | '/dashboard/nursing/consultation-fee/'
    | '/dashboard/nursing/doctor/'
    | '/dashboard/nursing/nurse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/catalog/department/': {
      id: '/dashboard/catalog/department/'
      path: '/catalog/department'
      fullPath: '/dashboard/catalog/department/'
      preLoaderRoute: typeof DashboardCatalogDepartmentIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/department/$departmentId': {
      id: '/dashboard/catalog/department/$departmentId'
      path: '/catalog/department/$departmentId'
      fullPath: '/dashboard/catalog/department/$departmentId'
      preLoaderRoute: typeof DashboardCatalogDepartmentDepartmentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/subdepartment/$subdepartmentId': {
      id: '/dashboard/catalog/subdepartment/$subdepartmentId'
      path: '/catalog/subdepartment/$subdepartmentId'
      fullPath: '/dashboard/catalog/subdepartment/$subdepartmentId'
      preLoaderRoute: typeof DashboardCatalogSubdepartmentSubdepartmentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/caregiver/': {
      id: '/dashboard/nursing/caregiver/'
      path: '/nursing/caregiver'
      fullPath: '/dashboard/nursing/caregiver/'
      preLoaderRoute: typeof DashboardNursingCaregiverIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/consultation-fee/': {
      id: '/dashboard/nursing/consultation-fee/'
      path: '/nursing/consultation-fee'
      fullPath: '/dashboard/nursing/consultation-fee/'
      preLoaderRoute: typeof DashboardNursingConsultationFeeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/doctor/': {
      id: '/dashboard/nursing/doctor/'
      path: '/nursing/doctor'
      fullPath: '/dashboard/nursing/doctor/'
      preLoaderRoute: typeof DashboardNursingDoctorIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/doctor/$doctorId': {
      id: '/dashboard/nursing/doctor/$doctorId'
      path: '/nursing/doctor/$doctorId'
      fullPath: '/dashboard/nursing/doctor/$doctorId'
      preLoaderRoute: typeof DashboardNursingDoctorDoctorIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/nurse/': {
      id: '/dashboard/nursing/nurse/'
      path: '/nursing/nurse'
      fullPath: '/dashboard/nursing/nurse/'
      preLoaderRoute: typeof DashboardNursingNurseIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCatalogDepartmentDepartmentIdRoute: typeof DashboardCatalogDepartmentDepartmentIdRoute
  DashboardCatalogSubdepartmentSubdepartmentIdRoute: typeof DashboardCatalogSubdepartmentSubdepartmentIdRoute
  DashboardNursingDoctorDoctorIdRoute: typeof DashboardNursingDoctorDoctorIdRoute
  DashboardCatalogDepartmentIndexRoute: typeof DashboardCatalogDepartmentIndexRoute
  DashboardNursingCaregiverIndexRoute: typeof DashboardNursingCaregiverIndexRoute
  DashboardNursingConsultationFeeIndexRoute: typeof DashboardNursingConsultationFeeIndexRoute
  DashboardNursingDoctorIndexRoute: typeof DashboardNursingDoctorIndexRoute
  DashboardNursingNurseIndexRoute: typeof DashboardNursingNurseIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCatalogDepartmentDepartmentIdRoute:
    DashboardCatalogDepartmentDepartmentIdRoute,
  DashboardCatalogSubdepartmentSubdepartmentIdRoute:
    DashboardCatalogSubdepartmentSubdepartmentIdRoute,
  DashboardNursingDoctorDoctorIdRoute: DashboardNursingDoctorDoctorIdRoute,
  DashboardCatalogDepartmentIndexRoute: DashboardCatalogDepartmentIndexRoute,
  DashboardNursingCaregiverIndexRoute: DashboardNursingCaregiverIndexRoute,
  DashboardNursingConsultationFeeIndexRoute:
    DashboardNursingConsultationFeeIndexRoute,
  DashboardNursingDoctorIndexRoute: DashboardNursingDoctorIndexRoute,
  DashboardNursingNurseIndexRoute: DashboardNursingNurseIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
