/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardNursingCaregiverIndexRouteImport } from './routes/dashboard/nursing/caregiver/index'
import { Route as DashboardNursingConsultationFeeIndexRouteImport } from './routes/dashboard/nursing/consultation-fee/index'
import { Route as DashboardNursingDoctorIndexRouteImport } from './routes/dashboard/nursing/doctor/index'
import { Route as DashboardNursingNurseIndexRouteImport } from './routes/dashboard/nursing/nurse/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNursingCaregiverIndexRoute =
  DashboardNursingCaregiverIndexRouteImport.update({
    id: '/nursing/caregiver/',
    path: '/nursing/caregiver/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingConsultationFeeIndexRoute =
  DashboardNursingConsultationFeeIndexRouteImport.update({
    id: '/nursing/consultation-fee/',
    path: '/nursing/consultation-fee/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingDoctorIndexRoute =
  DashboardNursingDoctorIndexRouteImport.update({
    id: '/nursing/doctor/',
    path: '/nursing/doctor/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingNurseIndexRoute =
  DashboardNursingNurseIndexRouteImport.update({
    id: '/nursing/nurse/',
    path: '/nursing/nurse/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/nursing/caregiver/': typeof DashboardNursingCaregiverIndexRoute
  '/dashboard/nursing/consultation-fee/': typeof DashboardNursingConsultationFeeIndexRoute
  '/dashboard/nursing/doctor/': typeof DashboardNursingDoctorIndexRoute
  '/dashboard/nursing/nurse/': typeof DashboardNursingNurseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/dashboard/nursing/caregiver': typeof DashboardNursingCaregiverIndexRoute
  '/dashboard/nursing/consultation-fee': typeof DashboardNursingConsultationFeeIndexRoute
  '/dashboard/nursing/doctor': typeof DashboardNursingDoctorIndexRoute
  '/dashboard/nursing/nurse': typeof DashboardNursingNurseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/nursing/caregiver/': typeof DashboardNursingCaregiverIndexRoute
  '/dashboard/nursing/consultation-fee/': typeof DashboardNursingConsultationFeeIndexRoute
  '/dashboard/nursing/doctor/': typeof DashboardNursingDoctorIndexRoute
  '/dashboard/nursing/nurse/': typeof DashboardNursingNurseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/nursing/caregiver/'
    | '/dashboard/nursing/consultation-fee/'
    | '/dashboard/nursing/doctor/'
    | '/dashboard/nursing/nurse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/nursing/caregiver'
    | '/dashboard/nursing/consultation-fee'
    | '/dashboard/nursing/doctor'
    | '/dashboard/nursing/nurse'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/nursing/caregiver/'
    | '/dashboard/nursing/consultation-fee/'
    | '/dashboard/nursing/doctor/'
    | '/dashboard/nursing/nurse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/nursing/caregiver/': {
      id: '/dashboard/nursing/caregiver/'
      path: '/nursing/caregiver'
      fullPath: '/dashboard/nursing/caregiver/'
      preLoaderRoute: typeof DashboardNursingCaregiverIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/consultation-fee/': {
      id: '/dashboard/nursing/consultation-fee/'
      path: '/nursing/consultation-fee'
      fullPath: '/dashboard/nursing/consultation-fee/'
      preLoaderRoute: typeof DashboardNursingConsultationFeeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/doctor/': {
      id: '/dashboard/nursing/doctor/'
      path: '/nursing/doctor'
      fullPath: '/dashboard/nursing/doctor/'
      preLoaderRoute: typeof DashboardNursingDoctorIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/nurse/': {
      id: '/dashboard/nursing/nurse/'
      path: '/nursing/nurse'
      fullPath: '/dashboard/nursing/nurse/'
      preLoaderRoute: typeof DashboardNursingNurseIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardNursingCaregiverIndexRoute: typeof DashboardNursingCaregiverIndexRoute
  DashboardNursingConsultationFeeIndexRoute: typeof DashboardNursingConsultationFeeIndexRoute
  DashboardNursingDoctorIndexRoute: typeof DashboardNursingDoctorIndexRoute
  DashboardNursingNurseIndexRoute: typeof DashboardNursingNurseIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardNursingCaregiverIndexRoute: DashboardNursingCaregiverIndexRoute,
  DashboardNursingConsultationFeeIndexRoute:
    DashboardNursingConsultationFeeIndexRoute,
  DashboardNursingDoctorIndexRoute: DashboardNursingDoctorIndexRoute,
  DashboardNursingNurseIndexRoute: DashboardNursingNurseIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
