/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardMedicalRecordsIndexRouteImport } from './routes/dashboard/medical-records/index'
import { Route as DashboardPatientsIndexRouteImport } from './routes/dashboard/patients/index'
import { Route as DashboardSettingIndexRouteImport } from './routes/dashboard/setting/index'
import { Route as DashboardVisitingDoctorVisitsRouteImport } from './routes/dashboard/visiting/doctor-visits'
import { Route as DashboardVisitingScheduleRouteImport } from './routes/dashboard/visiting/schedule'
import { Route as DashboardVisitingVideoConsultationRouteImport } from './routes/dashboard/visiting/video-consultation'
import { Route as DashboardCatalogDepartmentIndexRouteImport } from './routes/dashboard/catalog/department/index'
import { Route as DashboardCatalogDepartmentDepartmentIdRouteImport } from './routes/dashboard/catalog/department/$departmentId'
import { Route as DashboardCatalogSubdepartmentIndexRouteImport } from './routes/dashboard/catalog/subdepartment/index'
import { Route as DashboardCatalogSubdepartmentSubdepartmentIdRouteImport } from './routes/dashboard/catalog/subdepartment/$subdepartmentId'
import { Route as DashboardNursingCaregiverIndexRouteImport } from './routes/dashboard/nursing/caregiver/index'
import { Route as DashboardNursingConsultationFeeIndexRouteImport } from './routes/dashboard/nursing/consultation-fee/index'
import { Route as DashboardNursingDoctorIndexRouteImport } from './routes/dashboard/nursing/doctor/index'
import { Route as DashboardNursingDoctorDoctorIdRouteImport } from './routes/dashboard/nursing/doctor/$doctorId'
import { Route as DashboardNursingNurseIndexRouteImport } from './routes/dashboard/nursing/nurse/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMedicalRecordsIndexRoute =
  DashboardMedicalRecordsIndexRouteImport.update({
    id: '/medical-records/',
    path: '/medical-records/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPatientsIndexRoute = DashboardPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingIndexRoute = DashboardSettingIndexRouteImport.update({
  id: '/setting/',
  path: '/setting/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardVisitingDoctorVisitsRoute =
  DashboardVisitingDoctorVisitsRouteImport.update({
    id: '/visiting/doctor-visits',
    path: '/visiting/doctor-visits',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardVisitingScheduleRoute =
  DashboardVisitingScheduleRouteImport.update({
    id: '/visiting/schedule',
    path: '/visiting/schedule',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardVisitingVideoConsultationRoute =
  DashboardVisitingVideoConsultationRouteImport.update({
    id: '/visiting/video-consultation',
    path: '/visiting/video-consultation',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCatalogDepartmentIndexRoute =
  DashboardCatalogDepartmentIndexRouteImport.update({
    id: '/catalog/department/',
    path: '/catalog/department/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCatalogDepartmentDepartmentIdRoute =
  DashboardCatalogDepartmentDepartmentIdRouteImport.update({
    id: '/catalog/department/$departmentId',
    path: '/catalog/department/$departmentId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCatalogSubdepartmentIndexRoute =
  DashboardCatalogSubdepartmentIndexRouteImport.update({
    id: '/catalog/subdepartment/',
    path: '/catalog/subdepartment/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCatalogSubdepartmentSubdepartmentIdRoute =
  DashboardCatalogSubdepartmentSubdepartmentIdRouteImport.update({
    id: '/catalog/subdepartment/$subdepartmentId',
    path: '/catalog/subdepartment/$subdepartmentId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingCaregiverIndexRoute =
  DashboardNursingCaregiverIndexRouteImport.update({
    id: '/nursing/caregiver/',
    path: '/nursing/caregiver/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingConsultationFeeIndexRoute =
  DashboardNursingConsultationFeeIndexRouteImport.update({
    id: '/nursing/consultation-fee/',
    path: '/nursing/consultation-fee/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingDoctorIndexRoute =
  DashboardNursingDoctorIndexRouteImport.update({
    id: '/nursing/doctor/',
    path: '/nursing/doctor/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingDoctorDoctorIdRoute =
  DashboardNursingDoctorDoctorIdRouteImport.update({
    id: '/nursing/doctor/$doctorId',
    path: '/nursing/doctor/$doctorId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNursingNurseIndexRoute =
  DashboardNursingNurseIndexRouteImport.update({
    id: '/nursing/nurse/',
    path: '/nursing/nurse/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/visiting/doctor-visits': typeof DashboardVisitingDoctorVisitsRoute
  '/dashboard/visiting/schedule': typeof DashboardVisitingScheduleRoute
  '/dashboard/visiting/video-consultation': typeof DashboardVisitingVideoConsultationRoute
  '/dashboard/medical-records/': typeof DashboardMedicalRecordsIndexRoute
  '/dashboard/patients/': typeof DashboardPatientsIndexRoute
  '/dashboard/setting/': typeof DashboardSettingIndexRoute
  '/dashboard/catalog/department/$departmentId': typeof DashboardCatalogDepartmentDepartmentIdRoute
  '/dashboard/catalog/subdepartment/$subdepartmentId': typeof DashboardCatalogSubdepartmentSubdepartmentIdRoute
  '/dashboard/nursing/doctor/$doctorId': typeof DashboardNursingDoctorDoctorIdRoute
  '/dashboard/catalog/department/': typeof DashboardCatalogDepartmentIndexRoute
  '/dashboard/catalog/subdepartment/': typeof DashboardCatalogSubdepartmentIndexRoute
  '/dashboard/nursing/caregiver/': typeof DashboardNursingCaregiverIndexRoute
  '/dashboard/nursing/consultation-fee/': typeof DashboardNursingConsultationFeeIndexRoute
  '/dashboard/nursing/doctor/': typeof DashboardNursingDoctorIndexRoute
  '/dashboard/nursing/nurse/': typeof DashboardNursingNurseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/dashboard/visiting/doctor-visits': typeof DashboardVisitingDoctorVisitsRoute
  '/dashboard/visiting/schedule': typeof DashboardVisitingScheduleRoute
  '/dashboard/visiting/video-consultation': typeof DashboardVisitingVideoConsultationRoute
  '/dashboard/medical-records': typeof DashboardMedicalRecordsIndexRoute
  '/dashboard/patients': typeof DashboardPatientsIndexRoute
  '/dashboard/setting': typeof DashboardSettingIndexRoute
  '/dashboard/catalog/department/$departmentId': typeof DashboardCatalogDepartmentDepartmentIdRoute
  '/dashboard/catalog/subdepartment/$subdepartmentId': typeof DashboardCatalogSubdepartmentSubdepartmentIdRoute
  '/dashboard/nursing/doctor/$doctorId': typeof DashboardNursingDoctorDoctorIdRoute
  '/dashboard/catalog/department': typeof DashboardCatalogDepartmentIndexRoute
  '/dashboard/catalog/subdepartment': typeof DashboardCatalogSubdepartmentIndexRoute
  '/dashboard/nursing/caregiver': typeof DashboardNursingCaregiverIndexRoute
  '/dashboard/nursing/consultation-fee': typeof DashboardNursingConsultationFeeIndexRoute
  '/dashboard/nursing/doctor': typeof DashboardNursingDoctorIndexRoute
  '/dashboard/nursing/nurse': typeof DashboardNursingNurseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/visiting/doctor-visits': typeof DashboardVisitingDoctorVisitsRoute
  '/dashboard/visiting/schedule': typeof DashboardVisitingScheduleRoute
  '/dashboard/visiting/video-consultation': typeof DashboardVisitingVideoConsultationRoute
  '/dashboard/medical-records/': typeof DashboardMedicalRecordsIndexRoute
  '/dashboard/patients/': typeof DashboardPatientsIndexRoute
  '/dashboard/setting/': typeof DashboardSettingIndexRoute
  '/dashboard/catalog/department/$departmentId': typeof DashboardCatalogDepartmentDepartmentIdRoute
  '/dashboard/catalog/subdepartment/$subdepartmentId': typeof DashboardCatalogSubdepartmentSubdepartmentIdRoute
  '/dashboard/nursing/doctor/$doctorId': typeof DashboardNursingDoctorDoctorIdRoute
  '/dashboard/catalog/department/': typeof DashboardCatalogDepartmentIndexRoute
  '/dashboard/catalog/subdepartment/': typeof DashboardCatalogSubdepartmentIndexRoute
  '/dashboard/nursing/caregiver/': typeof DashboardNursingCaregiverIndexRoute
  '/dashboard/nursing/consultation-fee/': typeof DashboardNursingConsultationFeeIndexRoute
  '/dashboard/nursing/doctor/': typeof DashboardNursingDoctorIndexRoute
  '/dashboard/nursing/nurse/': typeof DashboardNursingNurseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/visiting/doctor-visits'
    | '/dashboard/visiting/schedule'
    | '/dashboard/visiting/video-consultation'
    | '/dashboard/medical-records/'
    | '/dashboard/patients/'
    | '/dashboard/setting/'
    | '/dashboard/catalog/department/$departmentId'
    | '/dashboard/catalog/subdepartment/$subdepartmentId'
    | '/dashboard/nursing/doctor/$doctorId'
    | '/dashboard/catalog/department/'
    | '/dashboard/catalog/subdepartment/'
    | '/dashboard/nursing/caregiver/'
    | '/dashboard/nursing/consultation-fee/'
    | '/dashboard/nursing/doctor/'
    | '/dashboard/nursing/nurse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/visiting/doctor-visits'
    | '/dashboard/visiting/schedule'
    | '/dashboard/visiting/video-consultation'
    | '/dashboard/medical-records'
    | '/dashboard/patients'
    | '/dashboard/setting'
    | '/dashboard/catalog/department/$departmentId'
    | '/dashboard/catalog/subdepartment/$subdepartmentId'
    | '/dashboard/nursing/doctor/$doctorId'
    | '/dashboard/catalog/department'
    | '/dashboard/catalog/subdepartment'
    | '/dashboard/nursing/caregiver'
    | '/dashboard/nursing/consultation-fee'
    | '/dashboard/nursing/doctor'
    | '/dashboard/nursing/nurse'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/visiting/doctor-visits'
    | '/dashboard/visiting/schedule'
    | '/dashboard/visiting/video-consultation'
    | '/dashboard/medical-records/'
    | '/dashboard/patients/'
    | '/dashboard/setting/'
    | '/dashboard/catalog/department/$departmentId'
    | '/dashboard/catalog/subdepartment/$subdepartmentId'
    | '/dashboard/nursing/doctor/$doctorId'
    | '/dashboard/catalog/department/'
    | '/dashboard/catalog/subdepartment/'
    | '/dashboard/nursing/caregiver/'
    | '/dashboard/nursing/consultation-fee/'
    | '/dashboard/nursing/doctor/'
    | '/dashboard/nursing/nurse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/medical-records/': {
      id: '/dashboard/medical-records/'
      path: '/medical-records'
      fullPath: '/dashboard/medical-records/'
      preLoaderRoute: typeof DashboardMedicalRecordsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/patients/': {
      id: '/dashboard/patients/'
      path: '/patients'
      fullPath: '/dashboard/patients/'
      preLoaderRoute: typeof DashboardPatientsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setting/': {
      id: '/dashboard/setting/'
      path: '/setting'
      fullPath: '/dashboard/setting/'
      preLoaderRoute: typeof DashboardSettingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/visiting/doctor-visits': {
      id: '/dashboard/visiting/doctor-visits'
      path: '/visiting/doctor-visits'
      fullPath: '/dashboard/visiting/doctor-visits'
      preLoaderRoute: typeof DashboardVisitingDoctorVisitsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/visiting/schedule': {
      id: '/dashboard/visiting/schedule'
      path: '/visiting/schedule'
      fullPath: '/dashboard/visiting/schedule'
      preLoaderRoute: typeof DashboardVisitingScheduleRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/visiting/video-consultation': {
      id: '/dashboard/visiting/video-consultation'
      path: '/visiting/video-consultation'
      fullPath: '/dashboard/visiting/video-consultation'
      preLoaderRoute: typeof DashboardVisitingVideoConsultationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/department/': {
      id: '/dashboard/catalog/department/'
      path: '/catalog/department'
      fullPath: '/dashboard/catalog/department/'
      preLoaderRoute: typeof DashboardCatalogDepartmentIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/department/$departmentId': {
      id: '/dashboard/catalog/department/$departmentId'
      path: '/catalog/department/$departmentId'
      fullPath: '/dashboard/catalog/department/$departmentId'
      preLoaderRoute: typeof DashboardCatalogDepartmentDepartmentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/subdepartment/': {
      id: '/dashboard/catalog/subdepartment/'
      path: '/catalog/subdepartment'
      fullPath: '/dashboard/catalog/subdepartment/'
      preLoaderRoute: typeof DashboardCatalogSubdepartmentIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/subdepartment/$subdepartmentId': {
      id: '/dashboard/catalog/subdepartment/$subdepartmentId'
      path: '/catalog/subdepartment/$subdepartmentId'
      fullPath: '/dashboard/catalog/subdepartment/$subdepartmentId'
      preLoaderRoute: typeof DashboardCatalogSubdepartmentSubdepartmentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/caregiver/': {
      id: '/dashboard/nursing/caregiver/'
      path: '/nursing/caregiver'
      fullPath: '/dashboard/nursing/caregiver/'
      preLoaderRoute: typeof DashboardNursingCaregiverIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/consultation-fee/': {
      id: '/dashboard/nursing/consultation-fee/'
      path: '/nursing/consultation-fee'
      fullPath: '/dashboard/nursing/consultation-fee/'
      preLoaderRoute: typeof DashboardNursingConsultationFeeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/doctor/': {
      id: '/dashboard/nursing/doctor/'
      path: '/nursing/doctor'
      fullPath: '/dashboard/nursing/doctor/'
      preLoaderRoute: typeof DashboardNursingDoctorIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/doctor/$doctorId': {
      id: '/dashboard/nursing/doctor/$doctorId'
      path: '/nursing/doctor/$doctorId'
      fullPath: '/dashboard/nursing/doctor/$doctorId'
      preLoaderRoute: typeof DashboardNursingDoctorDoctorIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nursing/nurse/': {
      id: '/dashboard/nursing/nurse/'
      path: '/nursing/nurse'
      fullPath: '/dashboard/nursing/nurse/'
      preLoaderRoute: typeof DashboardNursingNurseIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardVisitingDoctorVisitsRoute: typeof DashboardVisitingDoctorVisitsRoute
  DashboardVisitingScheduleRoute: typeof DashboardVisitingScheduleRoute
  DashboardVisitingVideoConsultationRoute: typeof DashboardVisitingVideoConsultationRoute
  DashboardMedicalRecordsIndexRoute: typeof DashboardMedicalRecordsIndexRoute
  DashboardPatientsIndexRoute: typeof DashboardPatientsIndexRoute
  DashboardSettingIndexRoute: typeof DashboardSettingIndexRoute
  DashboardCatalogDepartmentDepartmentIdRoute: typeof DashboardCatalogDepartmentDepartmentIdRoute
  DashboardCatalogSubdepartmentSubdepartmentIdRoute: typeof DashboardCatalogSubdepartmentSubdepartmentIdRoute
  DashboardNursingDoctorDoctorIdRoute: typeof DashboardNursingDoctorDoctorIdRoute
  DashboardCatalogDepartmentIndexRoute: typeof DashboardCatalogDepartmentIndexRoute
  DashboardCatalogSubdepartmentIndexRoute: typeof DashboardCatalogSubdepartmentIndexRoute
  DashboardNursingCaregiverIndexRoute: typeof DashboardNursingCaregiverIndexRoute
  DashboardNursingConsultationFeeIndexRoute: typeof DashboardNursingConsultationFeeIndexRoute
  DashboardNursingDoctorIndexRoute: typeof DashboardNursingDoctorIndexRoute
  DashboardNursingNurseIndexRoute: typeof DashboardNursingNurseIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardVisitingDoctorVisitsRoute: DashboardVisitingDoctorVisitsRoute,
  DashboardVisitingScheduleRoute: DashboardVisitingScheduleRoute,
  DashboardVisitingVideoConsultationRoute:
    DashboardVisitingVideoConsultationRoute,
  DashboardMedicalRecordsIndexRoute: DashboardMedicalRecordsIndexRoute,
  DashboardPatientsIndexRoute: DashboardPatientsIndexRoute,
  DashboardSettingIndexRoute: DashboardSettingIndexRoute,
  DashboardCatalogDepartmentDepartmentIdRoute:
    DashboardCatalogDepartmentDepartmentIdRoute,
  DashboardCatalogSubdepartmentSubdepartmentIdRoute:
    DashboardCatalogSubdepartmentSubdepartmentIdRoute,
  DashboardNursingDoctorDoctorIdRoute: DashboardNursingDoctorDoctorIdRoute,
  DashboardCatalogDepartmentIndexRoute: DashboardCatalogDepartmentIndexRoute,
  DashboardCatalogSubdepartmentIndexRoute:
    DashboardCatalogSubdepartmentIndexRoute,
  DashboardNursingCaregiverIndexRoute: DashboardNursingCaregiverIndexRoute,
  DashboardNursingConsultationFeeIndexRoute:
    DashboardNursingConsultationFeeIndexRoute,
  DashboardNursingDoctorIndexRoute: DashboardNursingDoctorIndexRoute,
  DashboardNursingNurseIndexRoute: DashboardNursingNurseIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
